#! /bin/sh

# This script typically modifies links or other files associated with
# foo, and/or removes files created by the package.

echo "TIMELAPSE: postrm"

if [ -L /etc/nginx/sites-enabled/timelapse_proxy ]; then
    unlink /etc/nginx/sites-enabled/timelapse_proxy
fi
rm -f /etc/nginx/sites-available/timelapse_proxy
