#! /bin/sh

# This script typically stops any daemons which are associated with a
# package. It is executed before the removal of files associated with
# the package.

echo "TIMELAPSE: prerm"

echo "Stopping NGINX..."
systemctl stop nginx
systemctl disable nginx

echo "Stopping TIMELAPSE..."
systemctl stop timelapse
systemctl disable timelapse
